apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: some-label-value
spec:
  containers:
    - name: awscli
      image: 366789379256.dkr.ecr.eu-west-1.amazonaws.com/amazon/aws-cli:latest
      command:
        - cat
      tty: true
    - name: docker
      image: 366789379256.dkr.ecr.eu-west-1.amazonaws.com/docker:dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
    - name: maven
      image: 366789379256.dkr.ecr.eu-west-1.amazonaws.com/mavenjdk:3.5.4
      command:
        - cat
      tty: true
      alwaysPullImage: false
      volumeMounts:
        - mountPath: /root/.m2/repository
          name: volume-0
      resources:
        requests:
          memory: 2048Mi
          cpu: 1200m
    - name: dynamodb
      image: 366789379256.dkr.ecr.eu-west-1.amazonaws.com/dynamodb_local:latest
      tty: true
    - name: mysql
      image: 366789379256.dkr.ecr.eu-west-1.amazonaws.com/mysql_local:latest
      tty: true
      env:
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: hdtbc649kmgtb4ds
        - name: MYSQL_ROOT_PASSWORD
          value: hdtbc649kmgtb4ds
    - name: selenium-node-chrome
      image: 366789379256.dkr.ecr.eu-west-1.amazonaws.com/selenium/standalone-chrome:3.141
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
  volumes:
    - name: volume-0
      persistentVolumeClaim:
        claimName: efs-claim-jenkins
    - name: dind-storage
      emptyDir: {}
    - name: dshm
      emptyDir:
        medium: Memory